### ISSUE TITLE
how to get the result of Small batches？

### ISSUE THREAD

**Issue by GuangtaoLyu** [line/MotionPatches#1]
thank you for your great work.
how to get the result of Small batches？
thank you.

**Comment by YU1ut** [comment]
Now you can use [scripts/test_batch.py](https://github.com/line/MotionPatches/blob/main/scripts/test_batch.py) to get the result of small batches with 32 samples.

**Comment by GuangtaoLyu** [comment]
> Now you can use [scripts/test_batch.py](https://github.com/line/MotionPatches/blob/main/scripts/test_batch.py) to get the result of small batches with 32 samples.

thank you
